import { Link, useSearchParams } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { Package, TriangleAlert, PackageX, ArrowDownToLine, Truck, ArrowLeftRight, SlidersHorizontal } from 'lucide-react';
import { useApi } from '../hooks/useApi';
import { Alert, Badge, date, Empty, Loading, PageHeader } from '../components/ui';

const colors = ['#526bff', '#ef233c', '#ffaf38', '#a1a6b3', '#33476a'];
const paths = { Receipt: 'receipts', Delivery: 'deliveries', Transfer: 'transfers', Adjustment: 'adjustments' };
function MovementChart({ rows }) {
  const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 6 + i); return { key: d.toLocaleDateString('en-CA'), label: d.toLocaleDateString('en-IN', { month: 'short', day: 'numeric' }) }; });
  const series = ['Receipt', 'Delivery', 'Adjustment'];
  const values = days.map(day => series.map(type => rows.filter(r => new Date(r.timestamp).toLocaleDateString('en-CA') === day.key && r.type === type).reduce((sum, r) => sum + Math.abs(r.quantityChange), 0)));
  const max = Math.max(10, ...values.flat());
  return <section className="panel movement-panel"><header className="panel-heading"><h2>Stock Movement</h2><span className="chart-period">Last 7 days</span></header><div className="chart-key">{series.map((s, i) => <span key={s}><i style={{ background: colors[i] }}/>{s === 'Receipt' ? 'Receipts' : s === 'Delivery' ? 'Deliveries' : 'Adjustments'}</span>)}</div><svg className="movement-chart" viewBox="0 0 460 220" role="img" aria-label="Stock movement by day, showing receipt, delivery and adjustment quantities"><title>Stock movement for the last seven days</title>{[0, 1, 2, 3].map(i => <g key={i}><line x1="42" x2="451" y1={174 - i * 48} y2={174 - i * 48} stroke="#eaf0f7"/><text x="32" y={178 - i * 48} textAnchor="end">{Math.round(max * i / 3)}</text></g>)}{days.map((d, i) => <g key={d.key}>{series.map((s, j) => <rect key={s} x={54 + i * 57 + j * 10} y={174 - values[i][j] / max * 144} width="7" height={values[i][j] / max * 144} rx="2" fill={colors[j]}><title>{d.label}: {s} {values[i][j]}</title></rect>)}<text x={68 + i * 57} y="198" textAnchor="middle">{d.label}</text></g>)}</svg>{!values.flat().some(Boolean) && <p className="chart-empty">Validated operations will appear here.</p>}</section>;
}
export default function DashboardPage({ reports = false }) {
  const { warehouses, locations, products } = useSelector(s => s.catalog);
  const [params, setParams] = useSearchParams();
  const filters = Object.fromEntries(params);
  const { data, loading, error } = useApi(`/dashboard?${params}`);
  const ledger = useApi('/ledger');
  const select = (key, label, options) => <select aria-label={label} value={filters[key] || ''} onChange={e => { const next = new URLSearchParams(params); e.target.value ? next.set(key, e.target.value) : next.delete(key); setParams(next); }}><option value="">{label}</option>{options.map(o => <option value={o.value || o} key={o.value || o}>{o.label || o}</option>)}</select>;
  const filteredProducts = products.filter(p => !filters.category || p.category === filters.category);
  const categories = [...new Set(filteredProducts.map(p => p.category))].map(name => ({ name, count: filteredProducts.filter(p => p.category === name && (!filters.location && !filters.warehouse || p.stock.some(s => (!filters.location || s.locationRef === filters.location) && (!filters.warehouse || locations.find(l => l.id === s.locationRef)?.warehouseRef === filters.warehouse)))).length })).filter(c => c.count);
  const total = categories.reduce((sum, c) => sum + c.count, 0);
  let accumulated = 0;
  const gradient = categories.map((c, i) => { const start = accumulated; accumulated += c.count / (total || 1) * 100; return `${colors[i % colors.length]} ${start}% ${accumulated}%`; }).join(',');
  const movements = (ledger.data || []).filter(r => (!filters.type || r.type === filters.type) && (!filters.status || r.status === filters.status) && (!filters.category || filteredProducts.some(p => p.id === r.product)) && (!filters.location || [r.fromLocation, r.toLocation].includes(filters.location)) && (!filters.warehouse || locations.some(l => l.warehouseRef === filters.warehouse && [r.fromLocation, r.toLocation].includes(l.id))));
  return <div className="reference-dashboard"><div className="dashboard-title-row"><PageHeader title={reports ? 'Inventory Reports' : 'Dashboard'} subtitle={reports ? 'Track your stock movements and inventory mix' : 'Overview of your inventory operations'}/><div className="filter-bar dashboard-filters">{select('type', 'All Document Types', ['Receipt', 'Delivery', 'Transfer', 'Adjustment'])}{select('status', 'All Status', ['Draft', 'Waiting', 'Ready', 'Done', 'Canceled'])}{select('warehouse', 'All Warehouses', warehouses.map(w => ({ value: w.id, label: w.name })))}</div></div><div className="dashboard-secondary-filters">{select('location', 'All Locations', locations.map(l => ({ value: l.id, label: l.name })))}{select('category', 'All Categories', [...new Set(products.map(p => p.category))])}{params.size > 0 && <button className="text-button" onClick={() => setParams({})}>Reset filters</button>}</div><Alert>{error}</Alert><Alert>{ledger.error}</Alert>{loading ? <Loading/> : data && <>
    <div className="reference-metrics">{[
      { label: 'Total Products', value: data.totalProducts, icon: Package, color: 'purple', to: '/products' },
      { label: 'Low Stock Items', value: data.lowStock, icon: TriangleAlert, color: 'amber', to: '/products?stock=Low%20Stock' },
      { label: 'Out of Stock Items', value: data.outOfStock, icon: PackageX, color: 'red', to: '/products?stock=Out%20of%20Stock' },
      { label: 'Pending Receipts', value: data.receipts.pending, icon: ArrowDownToLine, color: 'blue', to: '/receipts', detail: `${data.receipts.late} late / ${data.receipts.operations} operations` },
      { label: 'Pending Deliveries', value: data.deliveries.pending, icon: Truck, color: 'blue', to: '/deliveries', detail: `${data.deliveries.late} late / ${data.deliveries.operations} operations / ${data.deliveries.waiting} waiting` },
      { label: 'Scheduled Transfers', value: data.transfers.pending, icon: ArrowLeftRight, color: 'slate', to: '/transfers', detail: `${data.transfers.operations} operations` },
    ].map(({ label, value, icon: Icon, color, to, detail }) => <Link key={label} to={to} className="compact-metric"><span className={`metric-icon ${color}`}><Icon size={21}/></span><div><p>{label}</p><strong>{value.toLocaleString()}</strong>{detail && <small>{detail}</small>}</div></Link>)}</div>
    <div className="reference-dashboard-grid"><MovementChart rows={movements}/><section className="panel category-panel"><header className="panel-heading"><h2>Stock by Category</h2></header><div className="category-chart-body"><div className="donut" style={{ background: gradient ? `conic-gradient(${gradient})` : '#e8edf5' }}><div><strong>{total.toLocaleString()}</strong><small>Products</small></div></div><div className="legend">{categories.map((c, i) => <div key={c.name}><i style={{ background: colors[i % colors.length] }}/><span>{c.name}</span><strong>{c.count}</strong></div>)}</div></div></section><section className="panel recent-panel"><header className="panel-heading"><h2>Recent Activities</h2><Link to="/ledger">View All</Link></header>{data.recent.length ? <div className="activity-list">{data.recent.slice(0, 4).map(d => <Link key={d.id} to={`/${paths[d.type]}/${d.id}`} className="activity-row"><span className={`activity-icon ${d.type === 'Receipt' ? 'green' : d.type === 'Adjustment' ? 'red' : d.type === 'Transfer' ? 'amber' : 'purple'}`}>{d.type === 'Receipt' ? <ArrowDownToLine size={16}/> : d.type === 'Delivery' ? <Truck size={16}/> : <SlidersHorizontal size={16}/>}</span><div><strong>{d.reference}</strong><small>{d.contact}</small><Badge>{d.status}</Badge></div><time>{date(d.scheduleDate)}</time></Link>)}</div> : <Empty title="No recent operations"/>}</section></div><div className="dashboard-operation-links"><Link to="/receipts">Receipts <strong>{data.receipts.pending} to receive</strong></Link><Link to="/deliveries">Delivery Orders <strong>{data.deliveries.pending} to deliver</strong></Link><Link to="/products?stock=attention">Stock alerts <strong>{data.lowStock + data.outOfStock} products to review</strong></Link></div>
  </>}</div>;
}
