import { Link } from 'react-router-dom';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import { Package, TriangleAlert, PackageX, ArrowDownToLine, Truck, ArrowLeftRight, ArrowUpRight, ArrowRight, Clock, CircleCheck, CalendarDays } from 'lucide-react';
import { useApi } from '../hooks/useApi';
import { Alert, Badge, date, Empty, Loading, money, PageHeader } from '../components/ui';
export default function DashboardPage() {
  const { warehouses, locations, products } = useSelector(s => s.catalog), user = useSelector(s => s.auth.user);
  const [filters, setFilters] = useState({});
  const { data, loading, error, refresh } = useApi(`/dashboard?${new URLSearchParams(filters)}`);
  const select = (key, label, options) => <select aria-label={label} value={filters[key] || ''} onChange={e => setFilters({ ...filters, [key]: e.target.value })}><option value="">{label}</option>{options.map(o => <option value={o.value || o} key={o.value || o}>{o.label || o}</option>)}</select>;
  return <><PageHeader title="Dashboard" subtitle="A clear view of your inventory. A better start to your day." action="New Receipt" to="/receipts/new"/><div className="welcome-strip"><div><span className="greeting-dot"/>Good to see you, {user.name.split(' ')[0]}. <span>Here’s what’s happening in your workspace.</span></div><span><CalendarDays size={15}/>{date(new Date().toISOString())}</span></div><div className="filter-bar dashboard-filters">{select('type', 'All Document Types', ['Receipt', 'Delivery', 'Transfer', 'Adjustment'])}{select('status', 'All Statuses', ['Draft', 'Waiting', 'Ready', 'Done', 'Canceled'])}{select('warehouse', 'All Warehouses', warehouses.map(w => ({ value: w.id, label: w.name })))}{select('location', 'All Locations', locations.map(l => ({ value: l.id, label: l.name })))}{select('category', 'All Categories', [...new Set(products.map(p => p.category))])}<button className="text-button" onClick={() => { setFilters({}); refresh(); }}>Reset filters</button></div><Alert>{error}</Alert>{loading ? <Loading/> : data && <>
      <div className="metrics-grid">{[{ label: 'Total Products', value: data.totalProducts, Icon: Package, color: 'blue', note: 'Across your inventory', to: '/products' }, { label: 'Low Stock Items', value: data.lowStock, Icon: TriangleAlert, color: 'amber', note: 'Below reorder threshold', to: '/products?stock=Low%20Stock' }, { label: 'Out of Stock', value: data.outOfStock, Icon: PackageX, color: 'red', note: 'Require your attention', to: '/products?stock=Out%20of%20Stock' }, { label: 'Inventory Value', value: money(data.inventoryValue), Icon: Package, color: 'purple', note: 'Based on per unit cost', to: '/products' }].map(({ label, value, Icon, color, note, to }) => <Link to={to} key={label} className="metric-card"><div className="metric-top"><span className={`metric-icon ${color}`}><Icon size={20}/></span><ArrowUpRight size={17}/></div><p>{label}</p><strong>{value}</strong><small>{note}</small></Link>)}</div>
      <div className="section-title"><h2>Operations overview</h2><span>Keep things moving</span></div><div className="operations-grid">{[{ key: 'receipts', title: 'Receipts', verb: 'to receive', Icon: ArrowDownToLine, color: 'blue' }, { key: 'deliveries', title: 'Delivery Orders', verb: 'to deliver', Icon: Truck, color: 'purple' }, { key: 'transfers', title: 'Internal Transfers', verb: 'scheduled', Icon: ArrowLeftRight, color: 'teal' }].map(({ key, title, verb, Icon, color }) => <section className="operation-card" key={key}><div className="operation-title"><span className={`metric-icon ${color}`}><Icon size={19}/></span><h3>{title}</h3><Link to={`/${key}`} aria-label={`Open ${title}`}><ArrowUpRight size={18}/></Link></div><div className="operation-number">{data[key].pending}<span>{verb}</span></div><div className="operation-stats"><span className={data[key].late ? 'late' : ''}><Clock size={13}/>{data[key].late} late</span>{key === 'deliveries' && <span>{data[key].waiting} waiting</span>}<span>{data[key].operations} operations</span></div><Link className="operation-link" to={`/${key}`}>View {title.toLowerCase()}<ArrowRight size={15}/></Link></section>)}</div>
      <div className="dashboard-bottom"><section className="panel activity-panel"><header className="panel-heading"><div><h2>Recent operations</h2><p>The latest activity across your workspace</p></div><Link to="/ledger">View ledger <ArrowUpRight size={14}/></Link></header>{data.recent.length ? <div className="activity-list">{data.recent.map(d => <Link key={d.id} to={`/${{ Receipt: 'receipts', Delivery: 'deliveries', Transfer: 'transfers', Adjustment: 'adjustments' }[d.type]}/${d.id}`} className="activity-row"><span className={`activity-icon ${d.type === 'Receipt' ? 'blue' : 'purple'}`}>{d.type === 'Receipt' ? <ArrowDownToLine size={17}/> : <ArrowLeftRight size={17}/>}</span><div><strong>{d.reference}</strong><small>{d.contact}</small></div><span className="activity-date">{date(d.scheduleDate)}</span><Badge>{d.status}</Badge><ArrowUpRight size={15}/></Link>)}</div> : <Empty title="No operations for these filters"/>}</section><section className="panel stock-panel"><header className="panel-heading"><div><h2>Stock health</h2><p>Availability at a glance</p></div><CircleCheck size={18}/></header><div className="donut" style={{ background: `conic-gradient(#2775f7 0 ${data.inStock / (data.totalProducts || 1) * 100}%, #f8b83e 0 ${(data.inStock + data.lowStock) / (data.totalProducts || 1) * 100}%, #f16b7b 0 100%)` }}><div><strong>{data.totalProducts}</strong><small>Total products</small></div></div><div className="legend">{[['In Stock',data.inStock,'#2775f7'],['Low Stock',data.lowStock,'#f8b83e'],['Out of Stock',data.outOfStock,'#f16b7b']].map(([label,n,color]) => <div key={label}><i style={{ background: color }}/><span>{label}</span><strong>{n}</strong></div>)}</div></section></div><div className="insight-banner"><span className="metric-icon blue"><TriangleAlert size={19}/></span><div><strong>A little attention goes a long way.</strong><p>{data.lowStock + data.outOfStock} products need a stock review. Stay ahead of your next order.</p></div><Link to="/products?stock=attention">Review stock <ArrowRight size={16}/></Link></div>
    </>}</>;
}
