import { canManageOperation } from '../config/permissions';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { ArrowUpRight, CalendarDays } from 'lucide-react';
import { modules } from '../config/modules';
import { useApi } from '../hooks/useApi';
import { Alert, Badge, date, Kanban, Loading, PageHeader, SearchBox, Table, ViewToggle } from '../components/ui';
export default function DocumentListPage({ module }) {
  const manage = canManageOperation(useSelector(s => s.auth.user), module);
  const config = modules[module], { locations, warehouses } = useSelector(s => s.catalog);
  const { data, error, loading } = useApi(`/${module}`);
  const [search, setSearch] = useState(''), [status, setStatus] = useState(''), [view, setView] = useState('list'), [warehouse, setWarehouse] = useState(''), [after, setAfter] = useState(''), [before, setBefore] = useState('');
  const rows = (data || []).filter(d => `${d.reference} ${d.contact}`.toLowerCase().includes(search.toLowerCase()) && (!status || d.status === status) && (!warehouse || d.warehouseRef === warehouse) && (!after || d.scheduleDate >= after) && (!before || d.scheduleDate <= before));
  const loc = (id, fallback) => locations.find(l => l.id === id)?.name || fallback;
  const extra = module === 'transfers' || module === 'adjustments';
  return <><PageHeader title={config.title} subtitle={config.description} action={manage ? `New ${config.singular}` : undefined} to={`/${module}/new`}/><div className="summary-tabs"><button className={!status ? 'active' : ''} onClick={() => setStatus('')}>All {config.title.toLowerCase()}<span>{data?.length || 0}</span></button>{config.statuses.map(s => <button className={status === s ? 'active' : ''} key={s} onClick={() => setStatus(s)}>{s}<span>{(data || []).filter(d => d.status === s).length}</span></button>)}</div><section className="panel"><div className="filter-bar"><SearchBox value={search} onChange={setSearch}/><select aria-label="Filter by warehouse" value={warehouse} onChange={e => setWarehouse(e.target.value)}><option value="">All Warehouses</option>{warehouses.map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select><div className="date-range"><CalendarDays size={15}/><input aria-label="From schedule date" type="date" value={after} onChange={e => setAfter(e.target.value)}/><span>–</span><input aria-label="To schedule date" type="date" value={before} onChange={e => setBefore(e.target.value)}/></div><ViewToggle view={view} setView={setView}/></div><Alert>{error}</Alert>{loading ? <Loading/> : view === 'list' ? <Table columns={['Reference', 'From', 'To', config.type === 'Transfer' ? 'Vendor / Contact' : 'Contact', 'Schedule Date', ...(extra ? ['Quantity'] : []), 'Status', '']} rows={rows} renderRow={d => <tr key={d.id}><td><Link className="reference" to={`/${module}/${d.id}`}>{d.reference}</Link></td><td>{loc(d.fromLocation, module === 'receipts' ? 'Vendor' : '—')}</td><td>{loc(d.toLocation, module === 'deliveries' ? 'Customer' : '—')}</td><td>{d.contact}</td><td>{date(d.scheduleDate)}</td>{extra && <td>{d.lines.reduce((n, l) => n + l.quantity, 0)}</td>}<td><Badge>{d.status}</Badge></td><td><Link className="icon-button" aria-label={`Open ${d.reference}`} to={`/${module}/${d.id}`}><ArrowUpRight size={16}/></Link></td></tr>}/> : <Kanban rows={rows} statuses={config.statuses} renderCard={d => <Link className="kanban-card" key={d.id} to={`/${module}/${d.id}`}><strong>{d.reference}<ArrowUpRight size={14}/></strong><p>{d.contact}</p><small>{loc(d.fromLocation, 'Vendor')} → {loc(d.toLocation, 'Customer')}</small><footer><span>{date(d.scheduleDate)}</span><span>{d.lines.length} products</span></footer></Link>}/>}<div className="table-footer"><span>{rows.length} {rows.length === 1 ? 'record' : 'records'}</span><span>All changes stay in sync with your inventory</span></div></section></>;
}
