import { useState } from 'react';
import { useSelector } from 'react-redux';
import { Link } from 'react-router-dom';
import { useApi } from '../hooks/useApi';
import { Alert, Badge, date, Kanban, Loading, PageHeader, SearchBox, Table, ViewToggle } from '../components/ui';
const route = { Receipt: 'receipts', Delivery: 'deliveries', Transfer: 'transfers', Adjustment: 'adjustments' };
export default function LedgerPage() {
  const { data, error, loading } = useApi('/ledger'), { locations } = useSelector(s => s.catalog);
  const [search, setSearch] = useState(''), [type, setType] = useState(''), [location, setLocation] = useState(''), [view, setView] = useState('list'), [after, setAfter] = useState(''), [before, setBefore] = useState('');
  const rows = (data || []).filter(d => `${d.reference} ${d.contact} ${d.productName}`.toLowerCase().includes(search.toLowerCase()) && (!type || d.type === type) && (!location || [d.fromLocation,d.toLocation].includes(location)) && (!after || d.timestamp.slice(0, 10) >= after) && (!before || d.timestamp.slice(0, 10) <= before));
  const loc = (id, d, from) => locations.find(l => l.id === id)?.name || (d.type === 'Receipt' && from ? 'Vendor' : d.type === 'Delivery' && !from ? 'Customer' : 'Adjustment');
  return <><PageHeader title="Move History" subtitle="The full story of your stock. Every movement, recorded." action="New Movement" to="/transfers/new"/><section className="panel"><div className="filter-bar"><SearchBox value={search} onChange={setSearch} placeholder="Search Reference, Contact, or product…"/><select aria-label="Document type" value={type} onChange={e => setType(e.target.value)}><option value="">All Document Types</option>{Object.keys(route).map(t => <option key={t}>{t}</option>)}</select><select aria-label="Location" value={location} onChange={e => setLocation(e.target.value)}><option value="">All Locations</option>{locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select><div className="date-range"><input type="date" aria-label="From date" value={after} onChange={e => setAfter(e.target.value)}/><span>–</span><input type="date" aria-label="To date" value={before} onChange={e => setBefore(e.target.value)}/></div><ViewToggle view={view} setView={setView}/></div><Alert>{error}</Alert>{loading ? <Loading/> : view === 'list' ? <Table columns={['Reference', 'Contact', 'Schedule Date', 'Status', 'Product', 'From', 'To', 'Quantity', 'Date']} rows={rows} renderRow={d => <tr key={d.id} className={`ledger-${d.direction.toLowerCase()}`}><td><Link className="reference" to={`/${route[d.type]}/${d.relatedDocument}`}>{d.reference}</Link></td><td>{d.contact}</td><td>{date(d.scheduleDate)}</td><td><Badge>{d.status}</Badge></td><td>{d.productName}</td><td>{loc(d.fromLocation,d,true)}</td><td>{loc(d.toLocation,d,false)}</td><td><strong>{d.quantityChange > 0 ? '+' : ''}{d.quantityChange} <small>{d.direction}</small></strong></td><td>{date(d.timestamp)}<small className="block">{new Date(d.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</small></td></tr>}/> : <Kanban rows={rows} statuses={['Draft', 'Waiting', 'Ready', 'Done', 'Canceled']} renderCard={d => <Link className={`kanban-card ledger-${d.direction.toLowerCase()}`} to={`/${route[d.type]}/${d.relatedDocument}`} key={d.id}><strong>{d.reference}</strong><p>{d.productName} · {d.quantityChange > 0 ? '+' : ''}{d.quantityChange} {d.direction}</p><small>{d.contact}</small><p>{loc(d.fromLocation,d,true)} → {loc(d.toLocation,d,false)}</p><footer>{date(d.timestamp)}</footer></Link>}/>}<div className="table-footer"><span>{rows.length} movements · One row per product and direction</span><span><i className="legend-dot green"/>IN <i className="legend-dot red"/>OUT</span></div></section></>;
}
