import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Pencil, Warehouse, MapPin } from 'lucide-react';
import { useApi } from '../hooks/useApi';
import { api, errorMessage } from '../api/client';
import { loadCatalog } from '../store';
import { Alert, Field, Loading, Modal, PageHeader, SearchBox, Table } from '../components/ui';
export default function SettingsPage({ module }) {
  const isWarehouse = module === 'warehouses', title = isWarehouse ? 'Warehouses' : 'Locations', singular = isWarehouse ? 'Warehouse' : 'Location';
  const { data, error, loading, refresh } = useApi(`/${module}`), dispatch = useDispatch(), { warehouses } = useSelector(s => s.catalog);
  const [search, setSearch] = useState(''), [form, setForm] = useState(null), [modalError, setModalError] = useState(''), [busy, setBusy] = useState(false);
  const field = key => e => setForm({ ...form, [key]: e.target.value });
  async function save(e) { e.preventDefault(); setBusy(true); setModalError(''); try { await api[form.id ? 'put' : 'post'](`/${module}${form.id ? `/${form.id}` : ''}`, form); refresh(); dispatch(loadCatalog()); setForm(null); } catch (e) { setModalError(errorMessage(e)); } finally { setBusy(false); } }
  const rows = (data || []).filter(d => `${d.name} ${d.shortCode}`.toLowerCase().includes(search.toLowerCase()));
  return <><PageHeader title={title} subtitle={isWarehouse ? 'Organize your warehouses and keep every location connected.' : 'A place for everything. Manage rooms, racks, and storage areas.'} action={`Add ${singular}`} onClick={() => { setForm({ name: '', shortCode: '', address: '', warehouseRef: '' }); setModalError(''); }}/><section className="panel"><div className="filter-bar"><SearchBox value={search} onChange={setSearch} placeholder={`Search ${title.toLowerCase()}…`}/><span className="muted">{rows.length} {title.toLowerCase()}</span></div><Alert>{error}</Alert>{loading ? <Loading/> : <Table columns={['Name', 'Short Code', isWarehouse ? 'Address' : 'Warehouse', 'Actions']} rows={rows} renderRow={d => <tr key={d.id}><td><span className="product-name"><span className="product-thumb blue">{isWarehouse ? <Warehouse size={19}/> : <MapPin size={19}/>}</span><strong>{d.name}</strong></span></td><td><span className="code-tag">{d.shortCode}</span></td><td>{isWarehouse ? d.address : warehouses.find(w => w.id === d.warehouseRef)?.name}</td><td><button className="button small" onClick={() => { setForm(d); setModalError(''); }}><Pencil size={13}/>Edit</button></td></tr>}/>}</section>{form && <Modal title={`${form.id ? 'Edit' : 'Add'} ${singular}`} onClose={() => setForm(null)}><form onSubmit={save}><Alert>{modalError}</Alert><Field label="Name" required><input required value={form.name} onChange={field('name')}/></Field><Field label="Short Code" required><input required pattern="[A-Za-z0-9-]+" value={form.shortCode} onChange={field('shortCode')} placeholder={isWarehouse ? 'e.g. WH' : 'e.g. RACK-A'}/></Field>{isWarehouse ? <Field label="Address" required><textarea required rows={3} value={form.address} onChange={field('address')}/></Field> : <Field label="Warehouse" required><select required value={form.warehouseRef} onChange={field('warehouseRef')}><option value="">Select warehouse</option>{warehouses.map(w => <option value={w.id} key={w.id}>{w.name}</option>)}</select></Field>}<footer className="form-footer"><button type="button" className="button" onClick={() => setForm(null)}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : `Save ${singular}`}</button></footer></form></Modal>}</>;
}
