import { Router } from 'express';
import { authRoutes } from './authRoutes.js';
import { productRoutes } from './productRoutes.js';
import { operationRoutes } from './operationRoutes.js';
import { settingsRoutes } from './settingsRoutes.js';
import { ledgerRoutes } from './ledgerRoutes.js';
import { dashboardRoutes } from './dashboardRoutes.js';
import { authenticate } from '../middleware/authenticate.js';
export const api = Router();
api.use('/auth', authRoutes);
api.use(authenticate);
api.use('/products', productRoutes);
api.use(operationRoutes);
api.use(settingsRoutes);
api.use('/ledger', ledgerRoutes);
api.use('/dashboard', dashboardRoutes);
