import { Router } from 'express';
import * as products from '../controllers/productController.js';
import { managerOnly } from '../middleware/authorize.js';
export const productRoutes = Router();
productRoutes.get('/', products.list);
productRoutes.post('/', managerOnly, products.create);
productRoutes.get('/:id', products.detail);
productRoutes.put('/:id', managerOnly, products.update);
productRoutes.delete('/:id', managerOnly, products.remove);
productRoutes.post('/:id/stock', products.stock);
