import { auth } from '../services/index.js';
import { publicUser } from '../services/authService.js';
import { asyncHandler } from '../utils/asyncHandler.js';
export const signup = asyncHandler(async (req, res) => res.status(201).json(await auth.signup(req.body)));
export const login = asyncHandler(async (req, res) => res.json(await auth.login(req.body)));
export const logout = asyncHandler(async (req, res) => { await auth.logout(req.token); res.json({ message: 'Signed out.' }); });
export const me = asyncHandler(async (req, res) => res.json(publicUser(req.user)));
export const profile = asyncHandler(async (req, res) => res.json(await auth.profile(req.user, req.body)));
export const requestOtp = asyncHandler(async (req, res) => res.json(await auth.requestOtp(req.body)));
export const verifyOtp = asyncHandler(async (req, res) => res.json(await auth.verifyOtp(req.body)));
export const resetPassword = asyncHandler(async (req, res) => res.json(await auth.resetPassword(req.body)));
