import { useEffect, useState } from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { LayoutDashboard, Package, ArrowDownToLine, Truck, ArrowLeftRight, SlidersHorizontal, History, Warehouse, MapPin, ChevronDown, ChevronRight, Search, Bell, LogOut, UserRound, Menu, X, CircleHelp } from 'lucide-react';
import { Logo } from './ui';
import { api } from '../api/client';
import { loadCatalog, signedOut } from '../store';
const nav = [
  ['/','Dashboard', LayoutDashboard], ['/products','Products / Stock',Package],
  ['section','OPERATIONS'], ['/receipts','Receipts',ArrowDownToLine], ['/deliveries','Delivery Orders',Truck], ['/transfers','Internal Transfers',ArrowLeftRight], ['/adjustments','Stock Adjustments',SlidersHorizontal], ['/ledger','Move History',History],
  ['section','SETTINGS'], ['/warehouses','Warehouses',Warehouse], ['/locations','Locations',MapPin],
];
export default function Layout() {
  const dispatch = useDispatch(), navigate = useNavigate(), user = useSelector(s => s.auth.user);
  const [menu, setMenu] = useState(false), [mobile, setMobile] = useState(false), [search, setSearch] = useState('');
  useEffect(() => { dispatch(loadCatalog()); }, [dispatch]);
  async function logout() { try { await api.post('/auth/logout'); } finally { sessionStorage.removeItem('stocksense-token'); dispatch(signedOut()); navigate('/login'); } }
  return <div className="app-shell"><aside className={`sidebar ${mobile ? 'open' : ''}`}><div className="brand-row"><Logo/><button className="mobile-only icon-button" aria-label="Close navigation" onClick={() => setMobile(false)}><X size={18}/></button></div><div className="workspace-label"><span className="workspace-icon">S</span><div>StockSense workspace<small>Inventory management</small></div><ChevronDown size={15}/></div><nav>{nav.map(([to, label, Icon]) => to === 'section' ? <div className="nav-section" key={label}>{label}</div> : <NavLink key={to} to={to} end={to === '/'} onClick={() => setMobile(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><Icon size={18}/>{label}{to === '/receipts' && <span className="nav-dot"/>}</NavLink>)}</nav><div className="sidebar-bottom"><div className="help-card"><CircleHelp size={19}/><strong>A little more clarity.</strong><p>Every product. Every movement.<br/>All in one place.</p><NavLink to="/ledger">Explore your stock ledger <ChevronRight size={14}/></NavLink></div><NavLink to="/profile" className="nav-link"><UserRound size={18}/>My Profile</NavLink><button className="nav-link logout" onClick={logout}><LogOut size={18}/>Logout</button><div className="sidebar-footer"><span className="green-dot"/>Workspace connected <span>v1.0</span></div></div></aside>{mobile && <div className="sidebar-overlay" onClick={() => setMobile(false)}/>}
    <div className="main-shell"><header className="topbar"><button className="mobile-only icon-button" aria-label="Open navigation" onClick={() => setMobile(true)}><Menu size={22}/></button><form className="global-search" onSubmit={e => { e.preventDefault(); navigate(`/products?q=${encodeURIComponent(search)}`); }}><Search size={17}/><input aria-label="Search products" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search products, SKU, or categories…"/><kbd>↵</kbd></form><div className="topbar-right"><span className="workspace-status"><span className="green-dot"/>All systems operational</span><button className="notification icon-button" title="View low-stock alerts" aria-label="View low-stock alerts" onClick={() => navigate('/products?stock=Low%20Stock')}><Bell size={19}/><i/></button><div className="profile-wrap"><button className="profile-trigger" onClick={() => setMenu(!menu)} aria-expanded={menu}><span className="avatar">A</span><span className="profile-name">{user.name}<small>{user.role}</small></span><ChevronDown size={14}/></button>{menu && <div className="profile-dropdown"><NavLink to="/profile" onClick={() => setMenu(false)}><UserRound size={16}/>My Profile</NavLink><button onClick={logout}><LogOut size={16}/>Logout</button></div>}</div></div></header><main><Outlet/></main><footer className="main-footer"><span>StockSense <span className="muted">/</span> Inventory, in sync.</span><span>Built for better operations.</span></footer></div></div>;
}
